name: Docker Job Transformation

on:
  push:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run-docker-transformation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.transformation -t amazing-transformation .

      - name: Run container
        env:
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: docker run --rm amazing-transformation

  run-docker-clustering:
    runs-on: ubuntu-latest
    needs: run-docker-transformation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.clustering -t amazing-clustering .

      - name: Run container
        env:
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: docker run --rm amazing-clustering
